# Generated by Django 4.1.5 on 2023-04-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-created_at',)},
        ),
    ]
